export const ADD_CATEGORY = 'ADD_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const ADD_SUB_CATEGORY = 'ADD_SUB_CATEGORY';
export const TASKS_SHOW = 'TASKS_SHOW';
export const TASKS_DESCRIPTION_SHOW = 'TASKS_DESCRIPTION_SHOW';
export const TASKS_DESCRIPTION_UPDATE = 'TASKS_DESCRIPTION_UPDATE';
export const TASK_ADD = 'TASK_ADD';
